CFLAGS=-fsanitize=address -mfpmath=sse -fstack-protector-all -W -Wall -Wextra -Wunused -Wcast-align -Werror -pedantic -pedantic-errors -Wfloat-equal -Wpointer-arith -Wformat-security -Wmissing-format-attribute -Wformat=1 -Wwrite-strings -Wcast-align -Wno-long-long -Wmissing-declarations -lm -O3

LDFLAGS=-fsanitize=address

all: prog

prog: main.o io.o functions.o find_values.o
	g++ main.cpp io.o functions.o find_values.o $(LDFLAGS) -o main

io.o: io.cpp io.h
	g++ -c $(CFLAGS) io.cpp

functions.o: functions.cpp functions.h
	g++ -c $(CFLAGS) functions.cpp

find_values.o: find_values.cpp find_values.h
	g++ -c $(CFLAGS) find_values.cpp

main.o: main.cpp 
	g++ -c $(CFLAGS) main.cpp

clean:
	rm -rf *.o prog